### ISSUE TITLE
Boiling Water

### ISSUE THREAD

**Issue by jdgreen2** [vicuk/DAAP-intro-to-github#13]
- [x] Retrieve POT from the cabinet
- [x] Place POT in sink
- [x] Open Cold water
- [x] Fill POT to 1/2 full
- [x] Remove POT from Sink
- [x] Place POT on Burner
- [x] Turn on stove Burner

**Comment by idrmiller** [comment]
I don't think GSA has pots?

**Comment by jdgreen2** [comment]
You did not see the kitchen
