### ISSUE TITLE
Steps for Learning - SA

### ISSUE THREAD

**Issue by SriramAvasarala** [vicuk/DAAP-intro-to-github#5]
- [x] 1. Create a branch
- [x] 2. Add at least one commit
- [x] 3. Initiate pull request
- [x] 4. Collaborate with others
- [x] 5. Make one additional comment
- [x] 6. Merge the branch into master

**Comment by SriramAvasarala** [comment]
Done for the day!!!

**Comment by teri90** [comment]
:)

From: SriramAvasarala
Sent: Monday, June 6, 2016 4:56 PM
To: vicuk/DAAP-intro-to-github
Reply To: vicuk/DAAP-intro-to-github
Subject: Re: [vicuk/DAAP-intro-to-github] Steps for Learning - SA (#5)

Done for the day!!!
